#This is a unit test that test the first 6 methods from homework 1

require 'test/unit'
require 'misc.rb'

class String
  def is_permutation_of(other)
	#Checks if this string is a permutation of the passed in string
    self.split(//).sort == other.split(//).sort
  end
end

def getArrayFromPowersOfTwoGenerator(limit)
	#Method to create an array from the values generated by the powers of 2 method
	arr = []
	powers_of_two(limit) {|x| arr << x}
	return arr
end

def getArrayFromPowersGenerator(base, limit)
	#Method to create an array from the values generated by the powers method
	arr = []
	powers(base, limit) {|x| arr << x}
	return arr
end

class TestUtil < Test::Unit::TestCase

  def test_strip_vowels()
	#Test the strip vowels method
    assert_equal(strip_vowels(""), "");
    assert_equal(strip_vowels("ouT"), "T");
    assert_equal(strip_vowels("hello world"), "hll wrld");
    assert_equal(strip_vowels("aEIoUou"), "");
	assert_equal(strip_vowels("strip_VOWELS"), "strp_VWLS");
  end

  def test_scramble()
	#Test the scramble method
    ["", "a", "aaaa", "aaba", "abfswegwtewr"].each do |s|
      assert(s.is_permutation_of(scramble(s)))
    end
    assert(!"abc".is_permutation_of(scramble("aab")))
  end

  def test_powers_of_two()
	#Test the powers of two method
    assert_equal(getArrayFromPowersOfTwoGenerator(20), [1,2,4,8,16])
    assert_equal(getArrayFromPowersOfTwoGenerator(1111), [1,2,4,8,16,32,64,128,256,512,1024])
    assert_equal(getArrayFromPowersOfTwoGenerator(0), [])
    assert_equal(getArrayFromPowersOfTwoGenerator(5), [1,2,4])
  end

  def test_powers()
	#Test the powers of two method
	assert_equal(getArrayFromPowersGenerator(2,1111), [1,2,4,8,16,32,64,128,256,512,1024])
    assert_equal(getArrayFromPowersGenerator(3,400), [1,3,9,27,81,243])
    assert_equal(getArrayFromPowersGenerator(4,400), [1,4,16,64,256])
    assert_equal(getArrayFromPowersGenerator(5,0), [])
  end

  def test_interleave()
	#Test the interleave method
    assert_equal(interleave([1, 2], [nil, 5, 7, 10]), [1, nil, 2, 5, 7, 10])
    assert_equal(interleave([1, 'a', 'hello'], [nil, 23]), [1, nil, 'a', 23, 'hello'])
    assert_equal(interleave(['a', 'b', 'c', 'd'], ['e', 'f']), ['a', 'e', 'b', 'f', 'c', 'd'])
    assert_equal(interleave([1], [nil, nil, nil, 'q']), [1, nil, nil, nil, 'q'])
    assert_equal(interleave([1, 2, 3, 4, 5], [2, [3, 4]]), [1, 2, 2, [3, 4], 3, 4, 5])
  end

  def test_stutter()
	#Test the stutter method
    assert_equal([1, 1].stutter, [1, 1, 1, 1]);
    assert_equal([1, 2, 3, 4].stutter, [1, 1, 2, 2, 3, 3, 4, 4]);
    assert_equal([1, [2, 3], 'a'].stutter, [1, 1, [2, 3], [2, 3],  'a', 'a']);
    assert_equal([].stutter, []);
    assert_equal([nil].stutter, [nil, nil]);
    assert_equal([1, 'a', nil, true].stutter, [1, 1, 'a', 'a', nil, nil, true, true]);
  end

end